version: 0.2

env:
  variables:
    AWS_REGION: us-east-1
    CONTAINER_NAME: chatapp-frontend

phases:
  pre_build:
    commands:
      - echo "Logging to ECR"
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 600748199510.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=600748199510.dkr.ecr.us-east-1.amazonaws.com/dev/chatapp
      - BUILD_TAG=build-$CODEBUILD_BUILD_NUMBER
  
  build:
    commands:
      - cd ./fe
      - echo "building the docker image"
      - docker build -t $REPOSITORY_URI:$BUILD_TAG .

  post_build:
    commands:
      - echo "Pushing the Docker image to ECR"
      - docker push $REPOSITORY_URI:$BUILD_TAG
      - echo "Image $REPOSITORY_URI:$BUILD_TAG built and pushed successfully"
      - cd ..
      - echo Writing imagedefinitions.json...
      - printf '[{"name":"%s", "imageUri":"%s"}]' $CONTAINER_NAME $REPOSITORY_URI:$BUILD_TAG > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
    files: 
      - imagedefinitions.json
  
