version: '3.8'

services:
  backend:
    build: ./be/.
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=ankush123
      - DATABASE=test_db
    depends_on:
      - db
    networks:
      - app_network

  frontend:
    build: ./fe/.
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - API_BASE_URL=http://backend:5000/api
    networks:
      - app_network

  db:
    image: mysql
    container_name: "auth-app-db-1"
    environment:
      - MYSQL_ROOT_PASSWORD=ankush123
      - MYSQL_DATABASE=test_db
    ports:
      - "3306:3306"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
