services:

  frontend:
    build: ./fe/.
    container_name: "auth-app-frontend"
    # ports:
    #   - "3000:3000"
    expose:
      - "5000"
    depends_on:
      - backend
    environment:
      - API_BASE_URL=http://backend:5000
    # networks:
    #   - app_network

  backend:
    build: ./be/.
    container_name: "auth-app-backend"
    # ports:
    #   - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=Ankush9844.
      - DATABASE=auth_app
      - JWT_SECRET_KEY='eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1YiI6IkpvaG5ueSIsIlN1cm5hbWUiOiJSb2NrZXQiLCJFbWFpbCI6Impyb2NrZXRAZXhhbXBsZS5jb20iLCJSb2xlIjpbIk1hbmFnZXIiLCJQcm9qZWN0IEFkbWluaXN0cmF0b3IiXX0.RSq0eQtMWrxk4xxSiF8kD9B1L_8WExdEy-pCzrwSuYY'
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0
    container_name: "auth-app-db-1"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Ankush9844.
      - MYSQL_DATABASE=auth_app
    ports:
      - "3306:3306"
    command:
      - --server-id=223344
      - --log-bin=mysql-bin
      - --binlog_format=ROW
      - --binlog_row_image=FULL
      - --gtid_mode=ON
      - --enforce-gtid-consistency=ON
      - --bind-address=0.0.0.0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - frontend
    restart: always


