apiVersion: v1
kind: Secret
metadata:
  name: app-db-secret
  namespace: default
type: Opaque
data:
  DB_PASSWORD: dGVzdFBhc3N3b3Jk
  DB_USER: dGVzdFVzZXIxMjM=
  DATABASE: dGVzdF9kYg==
  JWT_SECRET_KEY: ZXlKMGVYQWlPaUpLVjFRaUxDSmhiR2NpT2lKSVV6STFOaUo5LmV5SnBjM01pT2lKUGJteHBibVVnU2xkVUlFSjFZaUk2SWtwdmFHNXVlU0lzSWxOMWNtNWhiV1VpT2lKU2IyTnJaWFFpTENKRmJXRnBiQ0k2SW1weWIyTnJaWFJBWlhoaGJYQnNaUzVqYjIwaUxDSlNiMnhsSWpwYklrMWhibUZuWlhJaUxDSlFjbTlxWldOMElFRmtiV2x1YVhOMGNtRjBiM0lpWFgwLlJTcTBlUXRNV3J4azR4eFNpRjhrRDlCMUxfOFdFeGRFeS1wQ3pyd1N1WVk=

  
