apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: db
  labels:
    app: mysql
    version: v1

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root123"
            - name: MYSQL_USER
              value: "testUser123"
            - name: MYSQL_PASSWORD
              value: "testPassword"
            - name: MYSQL_DATABASE
              value: "test_db"
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql

      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc

        # - name: mysql-init-script
        #   configMap:
        #     name: mysql-init-script

---

apiVersion: v1
kind: Service
metadata:
  name: mysql  # DNS name
  namespace: db
  labels:
    app: mysql
    version: v1
    
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:       # mysql Pod Should contain same labels
    app: mysql
    
  clusterIP: None 