apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-app-backend
  template:
    metadata:
      labels:
        app: chat-app-backend
    spec:
      containers:
      - name: chat-app-backend
        image: docker.io/developer9844/chat-app:backend_v3.0
        imagePullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: app-db-secret
        env:
          - name: DB_HOST
            value: 'mysql.db.svc.cluster.local'

        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: chat-app-backend-svc
spec:
  selector:
    app: chat-app-backend
  ports:
  - port: 5000
    targetPort: 5000
