apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-app-frontend
  template:
    metadata:
      labels:
        app: chat-app-frontend
    spec:
      containers:
      - name: chat-app-frontend
        image: docker.io/developer9844/chat-app:frontend_v1.0
        imagePullPolicy: IfNotPresent
        env:
          - name: API_BASE_URL
            value: 'http://chat-app-backend-svc.default.svc.cluster.local:5000/api'

        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: chat-app-frontend-svc
spec:
  selector:
    app: chat-app-frontend
  ports:
  - port: 3000
    targetPort: 3000
