apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Developer9844/auth_app.git
    targetRevision: HEAD
    path: k8s/auth-app
    helm:
      valueFiles:
        - values.yaml
        - values-sec.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true